export const SEO_CONFIG = {
  minimumQualityScore: 80,
  maximumSimilarityScore: 0.7,
  /** Measured useful content floors — not artificial 20k padding targets. */
  minimumWordCounts: {
    home: 800,
    core: 600,
    service: 1500,
    location: 900,
    area: 700,
    "service-in-city": 1500,
    "invisible-grills-installation-in-locality": 900,
    "service-location": 900,
    "service-area": 900,
    "service-area-intent": 700,
    solution: 800,
    "property-type": 800,
    guide: 800,
    blog: 600,
  } as Record<string, number>,
  titleMaxLength: 60,
  descriptionMaxLength: 160,
  descriptionMinLength: 110,
  crawlPriorities: {
    home: "critical",
    core: "high",
    service: "high",
    location: "high",
    "service-in-city": "high",
    "invisible-grills-installation-in-locality": "high",
    "service-location": "high",
    area: "medium",
    "service-area": "medium",
    "service-area-intent": "medium",
    solution: "medium",
    "property-type": "medium",
    guide: "medium",
    blog: "low",
  } as Record<string, "critical" | "high" | "medium" | "low">,
} as const;
