export const SEO_CONFIG = {
  minimumQualityScore: 80,
  maximumSimilarityScore: 0.7,
  /** Hard floor: every indexable SEO page must have at least 1,500 words. */
  minimumWordCounts: {
    home: 1500,
    core: 1500,
    service: 1500,
    location: 1500,
    area: 1500,
    "service-in-city": 1500,
    "invisible-grills-installation-in-locality": 1500,
    "service-location": 1500,
    "service-area": 1500,
    "service-area-intent": 1500,
    solution: 1500,
    "property-type": 1500,
    guide: 1500,
    blog: 1500,
  } as Record<string, number>,
  titleMaxLength: 60,
  descriptionMaxLength: 160,
  descriptionMinLength: 110,
  crawlPriorities: {
    home: "critical",
    core: "high",
    service: "high",
    location: "high",
    "service-in-city": "high",
    "invisible-grills-installation-in-locality": "high",
    "service-location": "high",
    area: "medium",
    "service-area": "medium",
    "service-area-intent": "medium",
    solution: "medium",
    "property-type": "medium",
    guide: "medium",
    blog: "low",
  } as Record<string, "critical" | "high" | "medium" | "low">,
} as const;
