export const SEO_CONFIG = {
  minimumQualityScore: 80,
  maximumSimilarityScore: 0.7,
  minimumWordCounts: {
    home: 20000,
    core: 20000,
    service: 20000,
    location: 20000,
    area: 20000,
    "service-in-city": 20000,
    "invisible-grills-installation-in-locality": 20000,
    "service-location": 20000,
    "service-area": 20000,
    "service-area-intent": 20000,
    solution: 20000,
    "property-type": 20000,
    guide: 20000,
    blog: 20000,
  } as Record<string, number>,
  titleMaxLength: 60,
  descriptionMaxLength: 160,
  descriptionMinLength: 110,
  crawlPriorities: {
    home: "critical",
    core: "high",
    service: "high",
    location: "high",
    "service-in-city": "high",
    "invisible-grills-installation-in-locality": "high",
    "service-location": "high",
    area: "medium",
    "service-area": "medium",
    "service-area-intent": "medium",
    solution: "medium",
    "property-type": "medium",
    guide: "medium",
    blog: "low",
  } as Record<string, "critical" | "high" | "medium" | "low">,
} as const;
