/** Auto-generated by scripts/build-service-images.mjs — do not edit manually. */
export type ServiceImageEntry = {
  heroImage: string;
  galleryImages: string[];
};

export type HomeGalleryItem = {
  src: string;
  serviceSlug: string;
};

export const SERVICE_IMAGE_CATALOG: Record<string, ServiceImageEntry> = {
  "invisible-grills": {
    "heroImage": "/images/services/invisible-grills/01-img-20251025-132727-jpg.jpeg",
    "galleryImages": [
      "/images/services/invisible-grills/01-img-20251025-132727-jpg.jpeg",
      "/images/services/invisible-grills/02-i1.png",
      "/images/services/invisible-grills/03-i3.jpg",
      "/images/services/invisible-grills/04-i5.jpg",
      "/images/services/invisible-grills/05-n50.jpg",
      "/images/services/invisible-grills/06-i4.jpg",
      "/images/services/invisible-grills/07-whatsapp-image-2026-06-26-at-10-08-15.jpeg",
      "/images/services/invisible-grills/08-n26.jpg",
      "/images/services/invisible-grills/09-whatsapp-image-2026-06-26-at-10-08-24.jpeg",
      "/images/services/invisible-grills/10-whatsapp-image-2026-06-26-at-10-07-27.jpeg",
      "/images/services/invisible-grills/11-i6.jpg",
      "/images/services/invisible-grills/12-whatsapp-image-2026-06-26-at-10-13-30.jpeg",
      "/images/services/invisible-grills/13-whatsapp-image-2026-06-26-at-10-07-26.jpeg",
      "/images/services/invisible-grills/14-whatsapp-image-2026-06-26-at-10-03-25.jpeg",
      "/images/services/invisible-grills/15-whatsapp-image-2026-06-26-at-10-03-36.jpeg",
      "/images/services/invisible-grills/16-whatsapp-image-2026-06-26-at-10-13-04.jpeg",
      "/images/services/invisible-grills/17-whatsapp-image-2026-06-26-at-10-13-51.jpeg",
      "/images/services/invisible-grills/18-whatsapp-image-2026-06-26-at-10-13-16.jpeg",
      "/images/services/invisible-grills/19-whatsapp-image-2026-06-26-at-10-13-48.jpeg",
      "/images/services/invisible-grills/20-whatsapp-image-2026-06-26-at-10-03-31.jpeg"
    ]
  },
  "balcony-safety-nets": {
    "heroImage": "/images/services/balcony-safety-nets/01-img-20251003-165138-jpg.jpeg",
    "galleryImages": [
      "/images/services/balcony-safety-nets/01-img-20251003-165138-jpg.jpeg",
      "/images/services/balcony-safety-nets/02-b2.jpg",
      "/images/services/balcony-safety-nets/03-b3.jpg",
      "/images/services/balcony-safety-nets/04-b-17.jpg",
      "/images/services/balcony-safety-nets/05-n53.jpg",
      "/images/services/balcony-safety-nets/06-whatsapp-image-2026-07-04-at-09-14-04.jpeg",
      "/images/services/balcony-safety-nets/07-b10.jpg",
      "/images/services/balcony-safety-nets/08-b1.jpg",
      "/images/services/balcony-safety-nets/09-b8.jpg",
      "/images/services/balcony-safety-nets/10-dc7.jpg",
      "/images/services/balcony-safety-nets/11-b15.jpg",
      "/images/services/balcony-safety-nets/12-dc8.jpg",
      "/images/services/balcony-safety-nets/13-indusrties-3.jpg",
      "/images/services/balcony-safety-nets/14-b5.jpg",
      "/images/services/balcony-safety-nets/15-b6.jpg",
      "/images/services/balcony-safety-nets/16-b13.jpg",
      "/images/services/balcony-safety-nets/17-car-1.jpg",
      "/images/services/balcony-safety-nets/18-b9.jpg",
      "/images/services/balcony-safety-nets/19-industries-2.jpg",
      "/images/services/balcony-safety-nets/20-img-20260214-wa0017.jpg"
    ]
  },
  "children-safety-nets": {
    "heroImage": "/images/services/children-safety-nets/01-child-1.jpg",
    "galleryImages": [
      "/images/services/children-safety-nets/01-child-1.jpg",
      "/images/services/children-safety-nets/02-child3.jpg",
      "/images/services/children-safety-nets/03-child2.jpg"
    ]
  },
  "pet-safety-nets": {
    "heroImage": "/images/services/pet-safety-nets/01-pet-2.jpg",
    "galleryImages": [
      "/images/services/pet-safety-nets/01-pet-2.jpg",
      "/images/services/pet-safety-nets/02-monkey-1.jpg",
      "/images/services/pet-safety-nets/03-img-20260214-wa0002.jpg",
      "/images/services/pet-safety-nets/04-pet-8.jpg",
      "/images/services/pet-safety-nets/05-istockphoto-1153489943-612x612.jpg",
      "/images/services/pet-safety-nets/06-b4.jpg",
      "/images/services/pet-safety-nets/07-pet-1.jpg",
      "/images/services/pet-safety-nets/08-pet-9.jpg",
      "/images/services/pet-safety-nets/09-pet-4.jpg",
      "/images/services/pet-safety-nets/10-pet-6.jpg"
    ]
  },
  "mosquito-nets": {
    "heroImage": "/images/services/mosquito-nets/01-n21.jpg",
    "galleryImages": [
      "/images/services/mosquito-nets/01-n21.jpg",
      "/images/services/mosquito-nets/02-mosq1.png",
      "/images/services/mosquito-nets/03-n22.webp"
    ]
  },
  "bird-spikes": {
    "heroImage": "/images/services/bird-spikes/01-spike3.webp",
    "galleryImages": [
      "/images/services/bird-spikes/01-spike3.webp",
      "/images/services/bird-spikes/02-spike8.jpg",
      "/images/services/bird-spikes/03-spike10.jpg"
    ]
  },
  "cloth-hangers": {
    "heroImage": "/images/services/cloth-hangers/01-cloth8.jpeg",
    "galleryImages": [
      "/images/services/cloth-hangers/01-cloth8.jpeg",
      "/images/services/cloth-hangers/02-cloth7.webp",
      "/images/services/cloth-hangers/03-whatsapp-image-2026-07-04-at-09-07-39.jpeg",
      "/images/services/cloth-hangers/04-cloth9.jpeg",
      "/images/services/cloth-hangers/05-cloth-1.jpg",
      "/images/services/cloth-hangers/06-cloth-2.jpg",
      "/images/services/cloth-hangers/07-cloth4.jpg",
      "/images/services/cloth-hangers/08-cloth6.webp"
    ]
  },
  "cricket-nets": {
    "heroImage": "/images/services/cricket-nets/01-n11.jpg",
    "galleryImages": [
      "/images/services/cricket-nets/01-n11.jpg",
      "/images/services/cricket-nets/02-sp-2.jpg",
      "/images/services/cricket-nets/03-n10.webp",
      "/images/services/cricket-nets/04-sp3.jpg"
    ]
  }
};

export const HOME_GALLERY_IMAGES: HomeGalleryItem[] = [
  {
    "src": "/images/services/invisible-grills/01-img-20251025-132727-jpg.jpeg",
    "serviceSlug": "invisible-grills"
  },
  {
    "src": "/images/services/invisible-grills/02-i1.png",
    "serviceSlug": "invisible-grills"
  },
  {
    "src": "/images/services/invisible-grills/03-i3.jpg",
    "serviceSlug": "invisible-grills"
  },
  {
    "src": "/images/services/balcony-safety-nets/01-img-20251003-165138-jpg.jpeg",
    "serviceSlug": "balcony-safety-nets"
  },
  {
    "src": "/images/services/balcony-safety-nets/02-b2.jpg",
    "serviceSlug": "balcony-safety-nets"
  },
  {
    "src": "/images/services/balcony-safety-nets/03-b3.jpg",
    "serviceSlug": "balcony-safety-nets"
  },
  {
    "src": "/images/services/children-safety-nets/01-child-1.jpg",
    "serviceSlug": "children-safety-nets"
  },
  {
    "src": "/images/services/children-safety-nets/02-child3.jpg",
    "serviceSlug": "children-safety-nets"
  },
  {
    "src": "/images/services/children-safety-nets/03-child2.jpg",
    "serviceSlug": "children-safety-nets"
  },
  {
    "src": "/images/services/pet-safety-nets/01-pet-2.jpg",
    "serviceSlug": "pet-safety-nets"
  },
  {
    "src": "/images/services/pet-safety-nets/02-monkey-1.jpg",
    "serviceSlug": "pet-safety-nets"
  },
  {
    "src": "/images/services/pet-safety-nets/03-img-20260214-wa0002.jpg",
    "serviceSlug": "pet-safety-nets"
  },
  {
    "src": "/images/services/mosquito-nets/01-n21.jpg",
    "serviceSlug": "mosquito-nets"
  },
  {
    "src": "/images/services/mosquito-nets/02-mosq1.png",
    "serviceSlug": "mosquito-nets"
  },
  {
    "src": "/images/services/mosquito-nets/03-n22.webp",
    "serviceSlug": "mosquito-nets"
  },
  {
    "src": "/images/services/bird-spikes/01-spike3.webp",
    "serviceSlug": "bird-spikes"
  },
  {
    "src": "/images/services/bird-spikes/02-spike8.jpg",
    "serviceSlug": "bird-spikes"
  },
  {
    "src": "/images/services/bird-spikes/03-spike10.jpg",
    "serviceSlug": "bird-spikes"
  },
  {
    "src": "/images/services/cloth-hangers/01-cloth8.jpeg",
    "serviceSlug": "cloth-hangers"
  },
  {
    "src": "/images/services/cloth-hangers/02-cloth7.webp",
    "serviceSlug": "cloth-hangers"
  },
  {
    "src": "/images/services/cloth-hangers/03-whatsapp-image-2026-07-04-at-09-07-39.jpeg",
    "serviceSlug": "cloth-hangers"
  },
  {
    "src": "/images/services/cricket-nets/01-n11.jpg",
    "serviceSlug": "cricket-nets"
  },
  {
    "src": "/images/services/cricket-nets/02-sp-2.jpg",
    "serviceSlug": "cricket-nets"
  },
  {
    "src": "/images/services/cricket-nets/03-n10.webp",
    "serviceSlug": "cricket-nets"
  }
];

export const HOME_HERO_IMAGE = "/images/services/invisible-grills/01-img-20251025-132727-jpg.jpeg";
